// SPDX-License-Identifier: AGPL-3.0-or-later

#include "Core.h"
#include "form_Main.h"

#include <QApplication>
#include <QDateTime>
#include <QDir>
#include <QElapsedTimer>
#include <QFile>
#include <QSettings>
#include <QStandardPaths>
#include <QTextStream>
#include <QtDebug>
#include <QtGui>

#include <getopt.h>
#include <unistd.h>

QString debugLogDir;

void enableDebugLogging(const QString &configPath);
void myMessageHandler(QtMsgType type, const QMessageLogContext &context, const QString &msg);

void help() {
  printf("\r\n%s\r\n\r\n"
         "  -h --help                           - Display this help\r\n"
         "  -p --profile <path to profile dir>  - Use specified profile dir (creates a new profile if non-existent)\r\n"
         "  -s --stylesheet <path to qss file>  - Use specified qss stylesheet\r\n"
         "\r\n",
         CLIENTNAME " v" CLIENTVERSION);
  exit(0);
}

int main(int argc, char *argv[]) {

// for configPath
#ifndef _WIN32
  constexpr auto NameOfConfigDirectoryOnLinux = "/.i2pchat/";
#endif

#if QT_VERSION >= 0x050600
  QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
#endif

  QApplication app(argc, argv);
  QString configPath;
  QFile styleSheetFile(":qss/Default.qss");

#ifdef ANDROID
  QStringList loc = QStandardPaths::standardLocations(QStandardPaths::GenericDataLocation);
  if (loc.size() <= 0) {
    QMessageBox::critical(NULL, "I2PChat", "Error: no USER folder found");
    app.exec();
    app.closeAllWindows();
    return 1;
  }
  QString configPathParent = loc.at(0);
  QDir configPathParentDir(configPathParent);
  QString configPathDir("i2pchat");
  configPath = configPathParent + "/" + configPathDir;
  if (!configPathParentDir.mkpath(configPathDir)) {
    QMessageBox::critical(NULL, "I2PChat", "Error: mkpath for config dir returned false");
    app.exec();
    app.closeAllWindows();
    return 1;
  }
#else

#ifdef _WIN32
  configPath = QStandardPaths::writableLocation(QStandardPaths::AppDataLocation);
#else
  configPath = QStandardPaths::writableLocation(QStandardPaths::HomeLocation) + NameOfConfigDirectoryOnLinux;
#endif

  { // getopt_long + getopt (short)

    int ret;
    int option_index;
    // :: = optional_argument ; = no_argument ; : = required_argument
    const char *short_options_optarg = "hb::p:s:";

    const struct option long_options_optarg[] = {{"help", no_argument, NULL, 'h'},
                                                 {"profile", required_argument, NULL, 'p'},
                                                 {"stylesheet", required_argument, NULL, 's'},
                                                 {NULL, 0, NULL, 0}};
    while ((ret = getopt_long(argc, argv, short_options_optarg, long_options_optarg, &option_index)) != -1) {

      switch (ret) {
      case 'h': {
        help();
        break;
      };
      case 'p': {
        configPath = QString(optarg);
        break;
      };
      case 's': {
        styleSheetFile.setFileName(optarg);
        break;
      };
      case '?':
      default: {
        help();
        break;
      };
      };
    };
  }

  {
    QDir configdir(configPath);
    if (!configdir.exists())
      configdir.mkpath(".");
  }

  if (QFile::exists(configPath + "/UseHomeForConfigStore") == true) {
    QStringList tmp = QStandardPaths::standardLocations(QStandardPaths::HomeLocation);
    if (!tmp.empty()) {
      configPath = tmp.at(0);
      configPath += "/.i2pchat";
    }
  }
#endif

  QDir().mkpath(configPath + "/themes/chat");
  QDir().mkpath(configPath + "/themes/app");

  // Write default theme CSS files — always overwrite on startup so defaults stay fresh.
  // Users who want custom themes should copy to a new .css file (file picker TBD).
  auto writeCss = [&](const QString &name, const QString &content) {
    QString path = configPath + "/themes/chat/" + name + ".css";
    QFile f(path);
    if (f.open(QIODevice::WriteOnly | QIODevice::Text)) {
      QTextStream out(&f);
      out << "/* ============================================================\n";
      out << " * I2PChat -- " << name << " (default theme)\n";
      out << " * ============================================================\n";
      out << " * DO NOT EDIT THIS FILE.\n";
      out << " * It is overwritten every time I2PChat starts -- all changes\n";
      out << " * will be lost on the next launch.\n";
      out << " *\n";
      out << " * To create a custom theme:\n";
      out << " *   1. Copy this file to a new name in themes/chat/\n";
      out << " *   2. Edit the copy\n";
      out << " *   3. Select it from Settings -> Chat Style\n";
      out << " * ============================================================ */\n";
      out << "\n";
      out << content;
      f.close();
    }
  };
  writeCss("Bubbles",
           ".bubble {\n"
           "  border-radius: 8px;\n"
           "  padding: 3px 8px;\n"
           "  box-shadow: 0 1px 2px rgba(0,0,0,0.15);\n"
           "  pad-v-inner: 2px;\n"
           "}\n"
           ".sent { background: #075e54; color: #ffffff; }\n"
           ".received { background: #e5e5ea; color: #1c1c1c; }\n"
           ".system { background: #e8e8e8; color: #888888; }\n"
           ".pending { background: #fff3cd; color: #856404; }\n"
           "\n"
           "/* Semantic message component classes */\n"
           "p, div, h1, h2, h3, h4, h5, h6, blockquote, pre, ul, ol, li { margin: 0; padding: 0; }\n"
            ".msg-header { font-size: smaller; padding: 1px 0; }\n"
            ".msg-icon { font-size: 12px; margin-right: 3px; vertical-align: middle; }\n"
            ".msg-time { font-size: smaller; opacity: 0.8; }\n"
            ".msg-sender { font-weight: bold; }\n");
  writeCss("Modern",
           ".bubble {\n"
           "  border-radius: 12px;\n"
           "  padding: 3px 8px;\n"
           "  box-shadow: 0 1px 2px rgba(0,0,0,0.15);\n"
           "  pad-v-inner: 2px;\n"
           "}\n"
           ".sent { background: #8774e1; color: #ffffff; }\n"
           ".received { background: #e8f0fe; color: #1c1c1c; }\n"
           ".system { background: #e8e8e8; color: #888888; }\n"
           ".pending { background: #fff3cd; color: #856404; }\n"
           "\n"
           "/* Semantic message component classes */\n"
           "p, div, h1, h2, h3, h4, h5, h6, blockquote, pre, ul, ol, li { margin: 0; padding: 0; }\n"
            ".msg-header { font-size: smaller; padding: 1px 0; }\n"
            ".msg-icon { font-size: 12px; margin-right: 3px; vertical-align: middle; }\n"
            ".msg-time { font-size: smaller; opacity: 0.8; }\n"
            ".msg-sender { font-weight: bold; }\n");

  enableDebugLogging(configPath);
  QTextCodec::setCodecForLocale(QTextCodec::codecForName("UTF-8"));

  form_MainWindow *mainForm = new form_MainWindow(configPath);

  {

    QSettings settings(configPath + "/application.ini", QSettings::IniFormat);
    settings.beginGroup("General");
    auto CurrentStyle = settings.value("current_Style", "Fusion").toString();
    auto CustomStyleSheet = settings.value("CustomStyleSheet", "").toString();
    settings.endGroup();
    qDebug() << "Curent style: " << CurrentStyle;
    mainForm->setStyle(QStyleFactory::create(CurrentStyle));
    if (CustomStyleSheet.size() > 1)
      styleSheetFile.setFileName(CustomStyleSheet);
  }

  mainForm->show();
  styleSheetFile.open(QFile::ReadOnly);
  app.setStyleSheet(styleSheetFile.readAll());
  app.exec();
  app.closeAllWindows();

  return 0;
}

void enableDebugLogging(const QString &configPath) {
  // is DebugPrint = enabled ?
  debugLogDir = configPath;
  QSettings settings(configPath + "/application.ini", QSettings::IniFormat);
  settings.beginGroup("General");
  if (settings.value("DebugLogging", "true").toBool() == true) {
    qInstallMessageHandler(myMessageHandler);
  }
  settings.endGroup();
  settings.sync();
}

void myMessageHandler(QtMsgType type, const QMessageLogContext &context, const QString &msg) {
  QString txt;

  txt.append(QDateTime::currentDateTime().toString("hh:mm:ss"));

  switch (type) {
  case QtDebugMsg: {
    txt.append(QString(" Debug: %1 (%2:%3, %4)\n").arg(msg).arg(context.file).arg(context.line).arg(context.function));
    break;
  }
  case QtWarningMsg: {
    txt.append(
      QString(" Warning: %1 (%2:%3, %4)\n").arg(msg).arg(context.file).arg(context.line).arg(context.function));
    break;
  }
  case QtCriticalMsg: {
    txt.append(
      QString(" Critical: %1 (%2:%3, %4)\n").arg(msg).arg(context.file).arg(context.line).arg(context.function));
    break;
  }
  case QtFatalMsg: {
    txt.append(QString(" Fatal: %1 (%2:%3, %4)\n").arg(msg).arg(context.file).arg(context.line).arg(context.function));
    break;
  }
  default: {
    txt.append(
      QString(" Message: %1 (%2:%3, %4)\n").arg(msg).arg(context.file).arg(context.line).arg(context.function));
    break;
  }
  }
  QFile outFile(debugLogDir + "/DebugLog.txt");
  outFile.open(QIODevice::WriteOnly | QIODevice::Append);
  QTextStream ts(&outFile);
  ts << txt << Qt::endl;
}
